### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by Alpslee** [liruiw/GenSim#1]
I run it on colab and got this:

raise KeyError(f"Environment variable '{key}' not found")
omegaconf.errors.InterpolationResolutionError: KeyError raised while resolving interpolation: "Environment variable 'GENSIM_ROOT' not found"
    full_key: hydra.run.dir
    object_type=dict

**Comment by liruiw** [comment]
Right. The repo is developed and used locally, and I haven't tried colab yet. The specific key problem can probably be solved with something like %env GENSIM_ROOT=%pwd
