### ISSUE TITLE
Tasks are different from those from Cliport repo

### ISSUE THREAD

**Issue by Flakeeeet** [liruiw/GenSim#10]
For example there isn't an **additional_reset()** function in **__ init __()** in cliport. Why they are different?

**Comment by liruiw** [comment]
That particular functions are added to unify the task script and improve LLM task generation success rates.

**Comment by Flakeeeet** [comment]
But when generating a task it returns **AttributeError: ${TaskName} object has no attribute 'additional_reset'**

**Comment by Flakeeeet** [comment]
<img width="415" alt="902cf00d27914841e845315071ff892" src="https://github.com/liruiw/GenSim/assets/105495377/b436d0d2-058a-447f-bcb6-a214e5eb036e">

Take buildhouse as example

**Comment by liruiw** [comment]
It should have that function because it inherits the task class. One possible reason is that your python path contains the original CLIPort code, and it's using that as the task source code rather than in this repo. Maybe you could take a look into that
