### ISSUE TITLE
No checkpoints in the google drive

### ISSUE THREAD

**Issue by Skvayzer** [liruiw/GenSim#11]
Readme.md says the pretrained multitask models can be found [here](https://drive.google.com/drive/folders/1RRSa4hXQKuN1ABuUVEdfV6urqZ99KZ57?usp=drive_link). But all folders there are empty or contain only json info of trainings.

Can you provide the weights for these checkpoints, please?

**Comment by liruiw** [comment]
Thanks for the note! I think my collaborators have uploaded all the pretrained models. Please take a look and let us know if you have further questions.
