### ISSUE TITLE
Exception: Failed to generate

### ISSUE THREAD

**Issue by zhuzj5** [liruiw/GenSim#13]
Hi, can you provide a detailed deployment tutorial? I may be having trouble with steps 2 and 3. How do I use the
2. export GENSIM_ROOT=$(pwd)
and 3. export OPENAI_KEY=YOUR KEY   ?

The following error occurs when running python gensim/run_simulation.py disp=True prompt_folder=vanilla_task_generation_prompt_simple :

Exception: Failed to generate

task creation time 0.002
task creation failure => count as syntax exceptions.
=========================================================
vanilla_task_generation_prompt_simple Trial 10 SYNTAX_PASS_RATE: 0.0% RUNTIME_PASS_RATE: 0.0% ENV_PASS_RATE: 0.0%
=========================================================
=========================================================
vanilla_task_generation_prompt_simple | TOTAL SYNTAX_PASS_RATE: 0.0% RUNTIME_PASS_RATE: 0.0% ENV_PASS_RATE: 0.0% DIVERSITE SCORE: 0.000
=========================================================
Model Folder:  output/output_stats/vanilla_task_generation_prompt_simple_27_05_2024_21:29:16
Total 0 New Tasks: []
Added 0  Tasks: []

**Comment by liruiw** [comment]
Thanks for your interest. I might need more context to help debug this. I think it could be due to either (1) failure of writing syntax-correct code (2) some other errors.
