### ISSUE TITLE
Wrong hyperlink in paper

### ISSUE THREAD

**Issue by L0Z1K** [liruiw/GenSim#4]
Hi. I want to let you know that in [your paper](https://arxiv.org/pdf/2310.01361.pdf), the link for github repo has a small typo.

<img width="726" alt="image" src="https://github.com/liruiw/GenSim/assets/64528476/70de2730-4689-487b-aeff-15b77ab505eb">

https://github.com/liruiw/Gen-Sim -> https://github.com/liruiw/GenSim

Btw, I like your project! :)

**Comment by liruiw** [comment]
Thanks a lot for catching the issue!
