### ISSUE TITLE
Can two robotic arms be generated to operate？

### ISSUE THREAD

**Issue by peppaaaaaaa** [liruiw/GenSim#8]
Sorry to bother you again. I am currently researching a project where robotic arms collaborate to complete tasks. I found that Gensim can complete individual robotic arm movements, but after researching the code, I did not find any code for setting the number of robotic arms. Can you tell me if this project can generate two robotic arms, or can the cliport successfully generate two robotic arms? Looking forward to your reply!

**Comment by liruiw** [comment]
Thanks for bringing this up. This robot setup follows CLIPort which uses a single arm. To extend to multiple arms, I think you can look into the environment code and modify the action and goal space of the environment. The GenSim pipeline is independent of the number of arms, as it only sets the scene and the start/goal in each action.
