### ISSUE TITLE
OpenGL installation

### ISSUE THREAD

**Issue by MaureenZOU** [liruiw/GenSim#9]
<img width="669" alt="Screenshot 2024-02-02 at 1 48 27 PM" src="https://github.com/liruiw/GenSim/assets/11957155/ce884e55-692d-43f2-9074-e53ee6fbe259">

Hi Authors, thanks for your interesting work : ) 

It would be appreciated if you could share any environment in which you are running this demo. I am using Linux with x11 forward to Mac machine, but it seems that an OpenGL error is reported. 

Thanks a lot!

**Comment by liruiw** [comment]
This is likely an environment setup problem. I wonder if the example scripts in pybullet work for you. If so, does the CLIPort scripts work for you?

**Comment by MaureenZOU** [comment]
I am exactly running the command python gensim/run_simulation.py disp=True prompt_folder=vanilla_task_generation_prompt_simple. I think it is an env problem, is there any way to save the generated video instead of visualizing the video? Thanks a lot!

**Comment by liruiw** [comment]
Yes you can add **disp=False** and **record.save_video=True** to the end of the command.

**Comment by MaureenZOU** [comment]
got it thanks!
